// <auto-generated />
using System;
using System.Collections.Generic;
using Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309000000_AddOrderFailedStatusAndRetryTracking")]
    partial class AddOrderFailedStatusAndRetryTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entities.OrderProductAffiliate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AffiliateId")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCodeSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CountdownExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CurrencyCodeSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryTimeSnapshot")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRetryAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NewCountdownExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderItemStatus")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryImageUrlSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("ProductBrandSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("ProductDescriptionSnapshot")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<double?>("ProductMaxPriceSnapshot")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProductMinPriceSnapshot")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductNameSnapshot")
                        .HasColumnType("text");

                    b.Property<decimal?>("ProductPriceSnapshot")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("ProductTypeSnapshot")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductVariantCombinationId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductVariantCombinationUidSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("ProfileUidSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("ProfileUsernameSnapshot")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ShippingCostSnapshot")
                        .HasColumnType("numeric");

                    b.Property<string>("ShippingProvider")
                        .HasColumnType("text");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariantTypesSnapshot")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AffiliateId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantCombinationId");

                    b.HasIndex("Uid");

                    b.ToTable("OrderProductAffiliates");
                });
#pragma warning restore 612, 618
        }
    }
}